services:
  app:
    # image: mcr.microsoft.com/devcontainers/base:dev-ubuntu26.04
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - hf-cache:/home/vscode/.cache/huggingface:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:8
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    depends_on:
      - redis

  mongodb:
    image: mongo:8
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb

  # Garage S3 Service
  garage:
    image: dxflrs/garage:v2.3.0
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      GARAGE_DEFAULT_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      GARAGE_DEFAULT_BUCKET: ${S3_BUCKET}
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    command:
      - /garage
      - server
      - --single-node
      - --default-bucket

  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

  imgproxy:
    image: darthsim/imgproxy:v3
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_MAX_SRC_RESOLUTION: ${IMGPROXY_MAX_SRC_RESOLUTION}
      IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
      IMGPROXY_S3_ENDPOINT: ${AWS_ENDPOINT_URL}
      IMGPROXY_S3_REGION: ${AWS_DEFAULT_REGION}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_USE_S3: true

  dex:
    image: ghcr.io/dexidp/dex:v2.45.1
    command: dex serve /etc/dex/cfg/config.yaml
    volumes:
      - ./dex-config.yaml:/etc/dex/cfg/config.yaml:ro

volumes:
  redis_data:
  mongo_data:
  garage-meta:
  garage-data:
  hf-cache:
